clc; clear; close all; 

QPs = [0 1 2 3 4 5 6 7 8 9 10 11];

CIFStatistics = {};
QCIFStatistics = {};

% config info
I_CIF = struct( ...
    'yuvInputFileName', 'CIF.yuv', ...
    'nFrame', 21, ...
    'width', 352, ...
    'height', 288, ...
    'blockSize', 16, ...
    'r', 16, ...
    'QPs', QPs, ...
    'I_Period', 1 , ...
    'nRefFrames', 1, ...
    'VBSEnable', true, ...
    'FMEEnable', true, ...
    'FastME', true, ...
    'visualizeVBS', false, ...
    'visualizeRGB', false, ...
    'visualizeMM', false, ...
    'visualizeNRF', false ...
    );

P_CIF = struct( ...
    'yuvInputFileName', 'CIF.yuv', ...
    'nFrame', 21, ...
    'width', 352, ...
    'height', 288, ...
    'blockSize', 16, ...
    'r', 16, ...
    'QPs', QPs, ...
    'I_Period', 21, ...
    'nRefFrames', 1, ...
    'VBSEnable', true, ...
    'FMEEnable', true, ...
    'FastME', true, ...
    'visualizeVBS', false, ...
    'visualizeRGB', false, ...
    'visualizeMM', false, ...
    'visualizeNRF', false ...
    );

I_QCIF = struct( ...
    'yuvInputFileName', 'QCIF.yuv', ...
    'nFrame', 21, ...
    'width', 176, ...
    'height', 144, ...
    'blockSize', 16, ...
    'r', 16, ...
    'QPs', QPs, ...
    'I_Period', 1, ...
    'nRefFrames', 1, ...
    'VBSEnable', true, ...
    'FMEEnable', true, ...
    'FastME', true, ...
    'visualizeVBS', false, ...
    'visualizeRGB', false, ...
    'visualizeMM', false, ...
    'visualizeNRF', false ...
    );

P_QCIF = struct( ...
    'yuvInputFileName', 'QCIF.yuv', ...
    'nFrame', 21, ...
    'width', 176, ...
    'height', 144, ...
    'blockSize', 16, ...
    'r', 16, ...
    'QPs', QPs, ...
    'I_Period', 21, ...
    'nRefFrames', 1, ...
    'VBSEnable', true, ...
    'FMEEnable', true, ...
    'FastME', true, ...
    'visualizeVBS', false, ...
    'visualizeRGB', false, ...
    'visualizeMM', false, ...
    'visualizeNRF', false ...
    );

% CIF IFrame
CIFStatistics{1} = getStatistics(I_CIF);

% CIF PFrame
CIFStatistics{2} = getStatistics(P_CIF);

% QCIF IFrame
QCIFStatistics{1} = getStatistics(I_QCIF);

% QCIF PFrame
QCIFStatistics{2} = getStatistics(P_QCIF);

save('CIFStatistics');
save('QCIFStatistics');


